[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
known_third_party = []

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.venv
    | \.vscode
  )/
)
'''

[tool.mypy]
ignore_missing_imports = true